services:
  restaurants.presentation.api:
    
    # ${DOCKER_IMAGE:-valeur_defaut} :
    #   Si la variable DOCKER_IMAGE est définie → utilise sa valeur
    #   Sinon → utilise 'yourusername/restaurant-api:latest'
    #   Le pipeline CI/CD injectera DOCKER_IMAGE avec le bon tag
    image: ${DOCKER_IMAGE:-yourusername/restaurant-api:latest}
    environment:
      - ConnectionStrings__RestaurantsDb=${DB_CONNECTION_STRING}
      - BlobStorage__ConnectionString=${BLOB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=${APP_ENV:-Production}

    depends_on:
      - sqlserver-container
      - azure-storage-emulator
    ports:
      - "${API_PORT:-5001}:8080" # Expose l'API sur le port 5001
    networks:
      - restaurant-network
    restart: unless-stopped


  sqlserver-container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "${SQL_PORT:-1433}:1433" # Expose SQL Server sur le port 1433
    volumes:
      - sqlserver-data:/var/opt/mssql  # Persistance des données
    networks:
      - restaurant-network
    restart: unless-stopped


  azure-storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    environment:
      - AZURITE_ACCOUNTS=${AZURITE_ACCOUNTS:-devstoreaccount1:restaurantStore123!}
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  sqlserver-data:
  azurite-data: